### PR TITLE
First shot at updating conveyorlc

### PR DESCRIPTION
**Pull request by vsoch**
This is the updated package file I'm working on that (hopefully) will install into a container with spack (not working yet). I accidentally also ran black on the entire package directory - sorry! Should just be formatting.

I'll open another PR (on GitLab) for my WIP Dockerfile that uses this in a few minutes - trying one more thing.

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
@XiaohuaZhangLLNL let's merge this - the analysis appears to be working, it's a huge improvement over the current working state, and I'll need it merged to test the entire build from start to finish (will start this build as soon as this is merged!) If we run into any other issues down the line I'll be happy to come back and do another PR.

**Comment by vsoch** [comment]
Thank you! :partying_face:

**Comment by XiaohuaZhangLLNL** [comment]
Thank you for getting this works in docker!

From: Vanessasaurus ***@***.***>
Date: Tuesday, December 20, 2022 at 4:44 PM
To: XiaohuaZhangLLNL/spack4atom ***@***.***>
Cc: Zhang, Xiaohua ***@***.***>, State change ***@***.***>
Subject: Re: [XiaohuaZhangLLNL/spack4atom] First shot at updating conveyorlc (PR #1)

Thank you! 🥳

**Comment by vsoch** [comment]
My pleasure! I love containers, please bug :bug: me if/when you ever want some help with them. :package:

**Pull request merged**
